<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<html>
<head>
  <title>8. 程式錯誤與例外(Exceptions)情形</title>
  
  <meta name="description" content="8. 程式錯誤與例外(Exceptions)情形 ">
 
  <meta name="keywords" content="tut">
 
  <meta name="resource-type" content="document">
 
  <meta name="distribution" content="global">
 
  <meta http-equiv="Content-Type" content="text/html; charset=Big5">
 
  <link rel="STYLESHEET" href="tut.css">
 
  <link rel="next" href="node11.html">
 
  <link rel="previous" href="node9.html">
 
  <link rel="up" href="tut.html">
 
  <link rel="next" href="node11.html">
</head>
 <body>
 
<div class="navigation">
<table align="Center" width="100%" cellpadding="0" cellspacing="2">
 <tbody>
    <tr>
 <td><a href="node9.html"><img src="previous.gif" border="0" height="32" alt="Previous Page" width="32"></a></td>
 <td><a href="tut.html"><img src="up.gif" border="0" height="32" alt="Up One Level" width="32"></a></td>
 <td><a href="node11.html"><img src="next.gif" border="0" height="32" alt="Next Page" width="32"></a></td>
 <td align="Center" width="100%">Python 教學文件</td>
 <td><a href="node2.html"><img src="contents.gif" border="0" height="32" alt="Contents" width="32"></a></td>
 <td><img src="blank.gif" border="0" height="32" alt="" width="32"></td>
 <td><img src="blank.gif" border="0" height="32" alt="" width="32"></td>
 </tr>
  </tbody>
</table>
 <b class="navlabel">Previous:</b> <a class="sectref" href="node9.html">7.
輸入(Input)與輸出(Output)</a> <b class="navlabel">Up:</b> <a class="sectref" href="tut.html">
Python 教學文件</a> <b class="navlabel">Next:</b> <a class="sectref" href="node11.html">
9. 類別(Classes)</a> <br>
<hr></div>
 <!--End of Navigation Panel--> <!--Table of Child-Links--> <a name="CHILD_LINKS"><strong>
Subsections </strong></a>  
<ul>
 
  <li><a name="tex2html339" href="node10.html#SECTION0010100000000000000000">
8.1 語法錯誤 </a> </li>
  <li><a name="tex2html340" href="node10.html#SECTION0010200000000000000000">
8.2 例外(Exceptions)情形 </a> </li>
  <li><a name="tex2html341" href="node10.html#SECTION0010300000000000000000">
8.3 例外(Exceptions)情形的處理 </a> </li>
  <li><a name="tex2html342" href="node10.html#SECTION0010400000000000000000">
8.4 如何引發例外(Exceptions) </a> </li>
  <li><a name="tex2html343" href="node10.html#SECTION0010500000000000000000">
8.5 自製一個例外情形 </a> </li>
  <li><a name="tex2html344" href="node10.html#SECTION0010600000000000000000">
8.6 定義善後的動作 </a> </li>
</ul>
 <!--End of Table of Child-Links--> 
<hr>  
<h1> <br>
 8. 程式錯誤與例外(Exceptions)情形  </h1>
  
<p> 至此為止，我們都只有稍稍的提到錯誤訊息。但是如果你有試著執行上面的範例的話，你可能注意到，基本上錯誤的情況可以分成兩類：語法錯誤 (  <i>
syntax errors</i> ) 以及例外情況 ( <i>exceptions</i> )。   </p>
<p>  </p>
<h1> <br>
 8.1 語法錯誤   </h1>
  
<p> 語法錯誤也叫做分析時的錯誤(parsing errors)，大概是一般在學Python時最常見到的直譯器所發出來的抱怨：   </p>
<p> </p>
<dl>
<dd><pre class="verbatim">&gt;&gt;&gt; while 1 print 'Hello world'<br>  File "&lt;stdin&gt;", line 1<br>    while 1 print 'Hello world'<br>                ^<br>SyntaxError: invalid syntax<br></pre>
  </dd>
  </dl>
  
  <p> Python分析器(parser)會在印出錯誤的行，並且用一個向上的箭號指出最早發現錯誤的地方，而這個錯誤是發生(至少是被發現)在這個箭號所指的單元(token)<i>
之前</i>。在我們的例子裡面：錯誤發生在 <tt class="keyword">print</tt> 這個關鍵字，因為前面應該有一個 ( "<tt class="character">
:</tt>" ) 。錯誤信息裡面也包含檔案名稱以及行數，所以你可以很快知道要到哪裡去找錯。   </p>
  <p>  </p>
  <h1> <br>
 8.2 例外(Exceptions)情形   </h1>
  
  <p> 有的時候，甚至當你的語法完全正確時，當你執行程式時仍然會出錯。這種在程式執行階段發生的錯誤叫做例外情形 ( <i>exceptions</i>
 ) ，並且會造成程式致命的終止(無法執行下去)。你待會就會知道在Python裡面要怎樣處理這樣的狀況，但是我們先來看這樣的狀況下會造成什麼錯誤信息： 
 </p>
  <p> </p>
  <dl>
  <dd><pre class="verbatim">&gt;&gt;&gt; 10 * (1/0)<br>Traceback (innermost last):<br>  File "&lt;stdin&gt;", line 1<br>ZeroDivisionError: integer division or modulo<br>&gt;&gt;&gt; 4 + spam*3<br>Traceback (innermost last):<br>  File "&lt;stdin&gt;", line 1<br>NameError: spam<br>&gt;&gt;&gt; '2' + 2<br>Traceback (innermost last):<br>  File "&lt;stdin&gt;", line 1<br>TypeError: illegal argument type for built-in operation<br></pre>
    </dd>
    </dl>
  
    <p> 在這些錯誤信息的最後一行都是解釋到底發生了什麼事。例外情況(Exception)有很多種類型，類型的名稱也在錯誤信息之中，在上面的例子裡面，exception的類型分別是：
 <tt class="exception">ZeroDivisionError</tt>, <tt class="exception">NameError</tt>
 以及  <tt class="exception">TypeError</tt>. 。對於內建的exception來說，這些印出來的字串都是這些內建的exception類型的真正類型名稱，但是對於使用者自己自定的exception類型就不一定了(雖然這是一個有用的約定俗成的習慣)。這些標準的exception名稱也正是他們內建的指稱(identifiers)
(不是正式的關鍵字)。  </p>
    <p> 這一行其他部分則是有關這個exception類型的詳細解釋，其意義則是依照exception的類型而有不同。   </p>
    <p> 在錯誤信息最後一行之前的部分則是顯示了這個exception發生時的狀況，也就是記憶體堆積(stack)的內容追朔(backtrace)。一般來說這個這個部分包含了stack
backtrace的來源行數，但是這並不代表是在從標準輸入讀入時候的行數。   </p>
    <p> 在Python程式庫參考手冊中( <i>Python Library Reference</i> )詳細列出了所有的內建exception及其說明。
  </p>
    <p>  </p>
    <h1> <br>
 8.3 例外(Exceptions)情形的處理  </h1>
  
    <p> 我們可以寫一個程式來處理某些的exception。請看下面程式範例，我們要求使用者輸入一個有效的數字，直到所輸入的數字真正有效為止。但是使用者也可以中止這個程式(用
    <kbd>Control-C</kbd> 或者是任何作業系統支援的方式)。值得注意的是，使用者主動中止程式事實上是使用者引發一個 <tt class="exception">
KeyboardInterrupt</tt> 的exception。   </p>
    <p> </p>
    <dl>
    <dd><pre class="verbatim">&gt;&gt;&gt; while 1:<br>...     try:<br>...         x = int(raw_input("Please enter a number: "))<br>...         break<br>...     except ValueError:<br>...         print "Oops! That was no valid number.  Try again..."<br>...<br></pre>
      </dd>
      </dl>
  
      <p> 這個  <tt class="keyword">try</tt> 敘述的作用如下： </p>
      <p>  </p>
      <ul>
 
        <li>首先，try之後的敘述( <i>try clause</i> ，在  <tt class="keyword">try</tt>
 及 <tt class="keyword">except</tt> 這兩個字之中所有的敘述)都會被執行。   
          <p>  </p>
        </li>
        <li>如果沒有發生任何exception， except之後的敘述( <i>except clause</i> )會自動被忽略，整個
 <tt class="keyword">try</tt> 敘述就算是執行完畢。  
          <p>  </p>
        </li>
        <li>如果當執行try之後的敘述時發生了exception，錯誤地方之後的敘述就不會被執行。然後如果這個exception的類型有某一個適合的
 <tt class="keyword">except</tt> 關鍵字之後的類型的話，就會執行這一個except之後的敘述，然後程式從整個 <tt class="keyword">
try</tt> 敘述之後的地方開始執行。   
          <p>  </p>
        </li>
        <li>如果所發生的exception在except關鍵字之後找不到相對應的類型時，系統會將這個類型傳給外面一層的 <tt class="keyword">
try</tt> 敘述。如果外層的exception處理機制不存在的話，這就是一個沒有被處理的exception( <i>unhandled exception</i>
 )，然後整個程式會中斷，並出現上面出現的錯誤程式。   
          <p>  </p>
        </li>
      </ul>
  
      <p> 一個  <tt class="keyword">try</tt> 敘述可以包含許多的except 部分來處理各種不同的exception，但是最多只有一個handler(譯：exception之後的敘述)會真正被執行。Handlers
只處理在所對應的  <tt class="keyword">try</tt> 部分發生的exception，其他的 try 部分發生的exception則不在處理範圍。一個except子句可以處理一個以上的exception，只要用list括弧把它們括起來。例如：
  </p>
      <p> </p>
      <dl>
      <dd><pre class="verbatim">... except (RuntimeError, TypeError, NameError):<br>...     pass<br></pre>
        </dd>
        </dl>
  
        <p> 最後的一個 except 可以不寫出exception 類型的名稱，這就當作是一個外卡(wildcard，譯：處理所有的exception)來使用。當使用時要特別的小心，因為如果你很有可能就把一個應該被注意的程式錯誤給隱藏起來了。你也可以在這個except子句裡面印出一個錯誤信息，然後把這個exception再丟(raise)出去(讓呼叫你程式的人來處理這個exception)。 
 </p>
        <p> </p>
        <dl>
        <dd><pre class="verbatim">import string, sys<br><br>try:<br>    f = open('myfile.txt')<br>    s = f.readline()<br>    i = int(string.strip(s))<br>except IOError, (errno, strerror):<br>    print "I/O error(%s): %s" % (errno, strerror)<br>except ValueError:<br>    print "Could not convert data to an integer."<br>except:<br>    print "Unexpected error:", sys.exc_info()[0]<br>    raise<br></pre>
          </dd>
          </dl>
  
          <p> 這個  <tt class="keyword">try</tt> ... <tt class="keyword">except</tt>
 的敘述有一個可有可無的else子句(  <i>else clause</i> )可以使用，當這個子句存在時，必須是放在所有的except clauses的後面。這個子句裡的敘述是當try子句沒有發生任何exception時，一定要執行的敘述。請看例子：
  </p>
          <p> </p>
          <dl>
          <dd><pre class="verbatim">for arg in sys.argv[1:]:<br>    try:<br>        f = open(arg, 'r')<br>    except IOError:<br>        print 'cannot open', arg<br>    else:<br>        print arg, 'has', len(f.readlines()), 'lines'<br>        f.close()<br></pre>
            </dd>
            </dl>
  
            <p> 使用 <tt class="keyword">else</tt> 要比在 <tt class="keyword">
try</tt> 子句裡面加入多餘的程式碼來的好，因為這樣減少意外的處理到那些不是由 <tt class="keyword">try</tt> ...
            <tt class="keyword">except</tt> 敘述中保護的程式碼所引發的exception。  </p>
            <p> 當一個exception 發生時，exception本身有一個 連帶的值，也叫做這個exception的參數( <i>
argument</i> )。至於這個參數是否存在以及其型態，則是由exception的類型所決定。對於有這個參數存在的exception類型來說，你可以在except
clause的後面加入一個名稱(或是list)來接收這個參數的值。請看下例：  </p>
            <p> </p>
            <dl>
            <dd><pre class="verbatim">&gt;&gt;&gt; try:<br>...     spam()<br>... except NameError, x:<br>...     print 'name', x, 'undefined'<br>... <br>name spam undefined<br></pre>
              </dd>
              </dl>
  
              <p> 如果一個exception 有一個參數的話，當它在沒有被處理，當作錯誤信息印出來的時候，就會成為最後(詳細解釋(`detail'))的一部份。 
 </p>
              <p> Exception的處理者(handlers，exception clause)並不只處理在try clause當中所發生的exception，也會處理所有在try
clause當中所(直接或間接)呼叫的函式所引發的exception。請看下例：   </p>
              <p> </p>
              <dl>
              <dd><pre class="verbatim">&gt;&gt;&gt; def this_fails():<br>...     x = 1/0<br>... <br>&gt;&gt;&gt; try:<br>...     this_fails()<br>... except ZeroDivisionError, detail:<br>...     print 'Handling run-time error:', detail<br>... <br>Handling run-time error: integer division or modulo<br></pre>
                </dd>
                </dl>
  
                <p>  </p>
                <h1> <br>
 8.4 如何引發例外(Exceptions)  </h1>
  
                <p> 使用  <tt class="keyword">raise</tt> 敘述可以引發一個特定的 exception，例如：
  </p>
                <p> </p>
                <dl>
                <dd><pre class="verbatim">&gt;&gt;&gt; raise NameError, 'HiThere'<br>Traceback (innermost last):<br>  File "&lt;stdin&gt;", line 1<br>NameError: HiThere<br></pre>
                  </dd>
                  </dl>
  
                  <p> <tt class="keyword">raise</tt> 的第一個參數是想要引發的exception的類型，第二個參數(可有可無)則是指定這個exception的參數值。
  </p>
                  <p>  </p>
                  <h1> <br>
 8.5 使用者自訂的例外(Exceptions)   </h1>
  
                  <p> 程式設計師可以自己命名自己想要的excetion，其方法是指定一個字串給一個變數，或者是自己創造一個新的exception類別來。舉例說明：
  </p>
                  <p> </p>
                  <dl>
                  <dd><pre class="verbatim">&gt;&gt;&gt; class MyError:<br>...     def __init__(self, value):<br>...         self.value = value<br>...     def __str__(self):<br>...         return `self.value`<br>... <br>&gt;&gt;&gt; try:<br>...     raise MyError(2*2)<br>... except MyError, e:<br>...     print 'My exception occurred, value:', e.value<br>... <br>My exception occurred, value: 4<br>&gt;&gt;&gt; raise MyError, 1<br>Traceback (innermost last):<br>  File "&lt;stdin&gt;", line 1<br>__main__.MyError: 1<br></pre>
                    </dd>
                    </dl>
  
                    <p> 許多標準的module都自己自訂其exception來報回(report)在他們自己所定義的函式裡面所發生的錯誤。
  </p>
                    <p> 有關於classes 更多的討論請看<a href="node11.html#classes">第九章</a>
``類別''。  </p>
                    <p>  </p>
                    <h1> <br>
 8.6 定義善後的動作  </h1>
  
                    <p> 在  <tt class="keyword">try</tt> 敘述的機制裡面有一個可有可無的子句(optional
clause)，其功用是在定義不管什麼情況發生下，你都得要做的清除善後的工作。 舉例來說：  </p>
                    <p> </p>
                    <dl>
                    <dd><pre class="verbatim">&gt;&gt;&gt; try:<br>...     raise KeyboardInterrupt<br>... finally:<br>...     print 'Goodbye, world!'<br>... <br>Goodbye, world!<br>Traceback (innermost last):<br>  File "&lt;stdin&gt;", line 2<br>KeyboardInterrupt<br></pre>
                      </dd>
                      </dl>
  
                      <p> 這個  <i>finally clause</i> 不管你的程式在try裡面是否有任何的exception發生都會被執行。當exception發生時，程式會執行finally
clause之後再引發這個exception。當程式的 <tt class="keyword">try</tt> try部分因為 <tt class="keyword">
break</tt> 或 <tt class="keyword">return</tt> 而離開時，finally clause也一樣會在離開的時候(``on
the way out'')被執行。   </p>
                      <p> 一個 <tt class="keyword">try</tt> 敘述機制應該要有一個或多個except
clauses，或者是有一個 finally clause，但是不能兩個都有。   </p>
                      <p>  </p>
                      <div class="navigation">
                      <table align="Center" width="100%" cellpadding="0" cellspacing="2">
 <tbody>
                          <tr>
 <td><a href="node9.html"><img src="previous.gif" border="0" height="32" alt="Previous Page" width="32"></a></td>
 <td><a href="tut.html"><img src="up.gif" border="0" height="32" alt="Up One Level" width="32"></a></td>
 <td><a href="node11.html"><img src="next.gif" border="0" height="32" alt="Next Page" width="32"></a></td>
 <td align="Center" width="100%">Python 教學文件</td>
 <td><a href="node2.html"><img src="contents.gif" border="0" height="32" alt="Contents" width="32"></a></td>
 <td><img src="blank.gif" border="0" height="32" alt="" width="32"></td>
 <td><img src="blank.gif" border="0" height="32" alt="" width="32"></td>
 </tr>
                        </tbody>
                      </table>
 <b class="navlabel">Previous:</b> <a class="sectref" href="node9.html">7.
輸入(Input)與輸出(Output)</a> <b class="navlabel">Up:</b> <a class="sectref" href="tut.html">
Python 教學文件</a> <b class="navlabel">Next:</b> <a class="sectref" href="node11.html">
9. 類別(Classes)</a> <br>
                      <hr></div>
 <!--End of Navigation Panel--> 
                      <address> </address>
                      <hr>請看<i><a href="about.html">關於此文件&hellip;</a></i>
 裡面有關如何給我們建議的說明。  
                      </body>
                      </html>
